# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d69bc3793129d85884979f827677ba7cd2501ad901044e0957408fe71fd7ab4b606b6ba5fb02ddc0d967be61900cbdef9ab225e457da6ad03a2a9050ef4afd9

test:
  secret_key_base: 89f423604969ef06897f0101e92e90ac8fb00b541f808cb31192e756a726a3675395eabec4aa24afce6e3f5a74da0cc9dbc6ada96c5fa7d6c68f0f1b94e268d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
